apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstoreapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstoreapi
  template:
    metadata:
      labels:
        app: bookstoreapi
    spec:
      containers:
      - name: bookstoreapi
        image: bookstoreapi:latest
        ports:
        - containerPort: 80
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"