name: java build pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout src code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookstore_api_src_code
          path: .

  build:
    needs: checkout
    runs-on: ubuntu-latest
      
    steps:  
      - name: download src code
        uses: actions/download-artifact@v4
        with:
          name: bookstore_api_src_code
          path: .

      - name: verify dir
        run: ls -lrt && pwd

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.organization=vidyavian95-ai
            -Dsonar.projectKey=vidyavian95-ai_BookStoreAPI
            -Dsonar.projectName=BookStoreAPI
            -Dsonar.java.binaries=target/classes 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build with Maven
        run: mvn clean verify com.github.spotbugs:spotbugs-maven-plugin:4.8.6.1:check

      - name: Run SpotBugs
        run: mvn spotbugs:spotbugs

      - name: Upload SpotBugs Report
        uses: lcollins/spotbugs-github-action@v3.2.0
        with:
            path: '**/spotbugsXml.xml'


      - name: Java installation
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: './pom.xml'

      - name: Maven build & Run Tests
        run: mvn clean verify -Dspring.profiles.active=test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build, tag, and push docker image to Amazon ECR 
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REGISTRY_ALIAS: demodevops
          REPOSITORY: bookstoreapi
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest

     # - name: Deploy to EB
     #   uses: aws-actions/aws-elasticbeanstalk-deploy@v1.0.2
     #   with:
     #       application-name: "demo-9271-2087-0716-bookstoreapi"
     #       environment-name: "Demo-9271-2087-0716-bookstoreapi-env"
     #       version-label: ${{ github.sha }}
     #       aws-region: "ap-south-1"
     #       deployment-package: Dockerrun.aws.json

      - name: deploy to EKs
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name bookstoreApi-cluster
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f deployment/service.yaml --validate=false
          kubectl apply -f deployment/ingress.yaml --validate=false

      - name: Verify deployment
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name demo-eks-cluster
          kubectl get all
      
      